# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 提取.py
# Created on: 2021-07-27 16:52:12.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

tifPath = r'D:\Temp\dirToDb\reproject'
outTifPath = r'D:\Temp\dirToDb\tiqu'
# Local variables:
inTif = os.path.join(tifPath,"vhi-2012-21.tif")

#
def tiqu(value):
    outTif = os.path.join(outTifPath,str(value) + ".tif")
    # Process: 计算字段
    arcpy.CalculateField_management(inTif, "TIQU", "Reclass( !Value! )",
                                    "PYTHON_9.3", "def Reclass(V):\\n    if V == " + str(value) + ":\\n        return 1\\n    else:\\n        return 0")
    # Process: 查找表
    arcpy.gp.Lookup_sa(inTif, "TIQU", outTif)

tiqu(1)
tiqu(2)
tiqu(3)
tiqu(4)
tiqu(5)